/// -------------------------------------------------------------------------------
/// THIS FILE IS ORIGINALLY GENERATED BY redis2go.py.
/// PLEASE DO NOT MODIFY THIS FILE.
/// -------------------------------------------------------------------------------

package main

import (
	"github.com/fananchong/go-redis-orm"
	"github.com/garyburd/redigo/redis"
	"github.com/golang/protobuf/proto"
	"strconv"
)

type RD_TestStruct2 struct {
	TestStruct2
}

func NewRD_TestStruct2(id int32) *RD_TestStruct2 {
	this := &RD_TestStruct2{}
	this.Id = id
	return this
}

func (this *RD_TestStruct2) Key() string {
	return "TestStruct2:" + strconv.FormatInt(int64(this.Id), 10)
}

func (this *RD_TestStruct2) Value() ([]byte, error) {
	return proto.Marshal(&this.TestStruct2)
}

func (this *RD_TestStruct2) Load(dbName string) error {
	db := go_redis_orm.GetDB(dbName)
	val, err := redis.String(db.Do("GET", this.Key()))
	if err == nil {
		err = proto.Unmarshal([]byte(val), &this.TestStruct2)
	}
	return err
}

func (this *RD_TestStruct2) Save(dbName string) error {
	db := go_redis_orm.GetDB(dbName)
	val, err := this.Value()
	if err == nil {
		_, err = db.Do("SET", this.Key(), val)
	}
	return err
}
