// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

/*
Package pbmsg is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	MsgEcho
	MsgLogin
	MsgLoginRet
*/
package pbmsg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Cmd int32

const (
	Cmd_Invaild Cmd = 0
	Cmd_Echo    Cmd = 1
	Cmd_Login   Cmd = 2
)

var Cmd_name = map[int32]string{
	0: "Invaild",
	1: "Echo",
	2: "Login",
}
var Cmd_value = map[string]int32{
	"Invaild": 0,
	"Echo":    1,
	"Login":   2,
}

func (x Cmd) String() string {
	return proto.EnumName(Cmd_name, int32(x))
}
func (Cmd) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MsgEcho struct {
	Text string `protobuf:"bytes,1,opt,name=Text" json:"Text,omitempty"`
}

func (m *MsgEcho) Reset()                    { *m = MsgEcho{} }
func (m *MsgEcho) String() string            { return proto.CompactTextString(m) }
func (*MsgEcho) ProtoMessage()               {}
func (*MsgEcho) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MsgEcho) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type MsgLogin struct {
	Account  string `protobuf:"bytes,1,opt,name=Account" json:"Account,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
}

func (m *MsgLogin) Reset()                    { *m = MsgLogin{} }
func (m *MsgLogin) String() string            { return proto.CompactTextString(m) }
func (*MsgLogin) ProtoMessage()               {}
func (*MsgLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MsgLogin) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *MsgLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type MsgLoginRet struct {
	OK int32 `protobuf:"varint,1,opt,name=OK" json:"OK,omitempty"`
}

func (m *MsgLoginRet) Reset()                    { *m = MsgLoginRet{} }
func (m *MsgLoginRet) String() string            { return proto.CompactTextString(m) }
func (*MsgLoginRet) ProtoMessage()               {}
func (*MsgLoginRet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MsgLoginRet) GetOK() int32 {
	if m != nil {
		return m.OK
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgEcho)(nil), "pbmsg.MsgEcho")
	proto.RegisterType((*MsgLogin)(nil), "pbmsg.MsgLogin")
	proto.RegisterType((*MsgLoginRet)(nil), "pbmsg.MsgLoginRet")
	proto.RegisterEnum("pbmsg.Cmd", Cmd_name, Cmd_value)
}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0x48, 0xca, 0x2d, 0x4e, 0x57, 0x92, 0xe5,
	0x62, 0xf7, 0x2d, 0x4e, 0x77, 0x4d, 0xce, 0xc8, 0x17, 0x12, 0xe2, 0x62, 0x09, 0x49, 0xad, 0x28,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x1c, 0xb8, 0x38, 0x7c, 0x8b, 0xd3,
	0x7d, 0xf2, 0xd3, 0x33, 0xf3, 0x84, 0x24, 0xb8, 0xd8, 0x1d, 0x93, 0x93, 0xf3, 0x4b, 0xf3, 0x60,
	0x4a, 0x60, 0x5c, 0x21, 0x29, 0x2e, 0x8e, 0x80, 0xc4, 0xe2, 0xe2, 0xf2, 0xfc, 0xa2, 0x14, 0x09,
	0x26, 0xb0, 0x14, 0x9c, 0xaf, 0x24, 0xcb, 0xc5, 0x0d, 0x33, 0x21, 0x28, 0xb5, 0x44, 0x88, 0x8f,
	0x8b, 0xc9, 0xdf, 0x1b, 0xac, 0x9f, 0x35, 0x88, 0xc9, 0xdf, 0x5b, 0x4b, 0x9d, 0x8b, 0xd9, 0x39,
	0x37, 0x45, 0x88, 0x9b, 0x8b, 0xdd, 0x33, 0xaf, 0x2c, 0x31, 0x33, 0x27, 0x45, 0x80, 0x41, 0x88,
	0x83, 0x8b, 0x05, 0xe4, 0x20, 0x01, 0x46, 0x21, 0x4e, 0x2e, 0x56, 0xb0, 0x4e, 0x01, 0xa6, 0x24,
	0x36, 0xb0, 0xb3, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x98, 0x9b, 0xac, 0x82, 0xc4, 0x00,
	0x00, 0x00,
}
