// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TestStruct1.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	TestStruct1.proto
	TestStruct2.proto

It has these top-level messages:
	TestStruct1
	TestStruct2
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestStruct1 struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	F1 string `protobuf:"bytes,2,opt,name=f1" json:"f1,omitempty"`
}

func (m *TestStruct1) Reset()                    { *m = TestStruct1{} }
func (m *TestStruct1) String() string            { return proto.CompactTextString(m) }
func (*TestStruct1) ProtoMessage()               {}
func (*TestStruct1) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TestStruct1) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TestStruct1) GetF1() string {
	if m != nil {
		return m.F1
	}
	return ""
}

func init() {
	proto.RegisterType((*TestStruct1)(nil), "main.TestStruct1")
}

func init() { proto.RegisterFile("TestStruct1.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 86 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0c, 0x49, 0x2d, 0x2e,
	0x09, 0x2e, 0x29, 0x2a, 0x4d, 0x2e, 0x31, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9,
	0x4d, 0xcc, 0xcc, 0x53, 0xd2, 0xe5, 0xe2, 0x46, 0x92, 0x12, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x01, 0xf1, 0xd3, 0x0c, 0x25, 0x98, 0x20,
	0xfc, 0x34, 0xc3, 0x24, 0x36, 0xb0, 0x5e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x86, 0x0f,
	0xff, 0x69, 0x50, 0x00, 0x00, 0x00,
}
